### ISSUE TITLE
settings.py.example sisältää salasanan postgresql kannalle. 

### ISSUE THREAD

**Issue by Mudi** [pekko/kirjaaja#1]
Rivi 26 tiedostossa "settings.py.example" sisältää pecko.dy.fi palvelimelle täydet tunnukset.

**Comment by pekko** [comment]
Kiitos! Korjasin ja vaihdoin salasanan, onneksi ulkopuolelta ei päässyt sinne kiinni. En lähtenyt leikkimään historian kanssa, jääköön opetukseksi jälkipolville
